### ISSUE TITLE
T37 Ohjeet miten mittayksikköjä käsitellään

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#117]
Paikkatietoasiantuntijana haluan tietää, miten luodaan kaksiajoratainen päätie, jotta voin sellaisen tehdä, koska Katja-asetuksessa ei ole tälle ohjetta.

Kysytty, mutta ei vielä tiedossa vastausta ==> Katja-asetuksessa yleiskaavan osalta määritelty, että kaavamääräyslaji on omansa eli Kaksiajratainen tie tai katu. Ei vaadi toimenpiteitä. 

```[tasklist]
### Tasks
- [x] Kysytty Sykeltä, vastauksena että Katja-asetus kertoo - ei kerro
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/236
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/114
```

**Comment by SannaJokela** [comment]
uusi kaavamääräyslaji tullut, ei tarvetta toimenpiteille.
