### ISSUE TITLE
T60 Kaavaselosteeseen ja selitteeseen kaavatiedot kootusti

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#131]
Paikkatietoasiantuntijana haluan, että kaavaselosteeseen ja kaavan selitteeseen voidaan tuoda järjestelmästä kaavatiedot kootusti, jotta minun ei tarvitse osata yhdistellä tietoja itse, koska en osaa SQLää.

Kaavatietomallin avulla ei voi suoraan tuoda kaikkea haluttua tietoa karttaselitteeseen, koska tiedot tulevat useasta eri taulusta. Tämän vuoksi tarvitaan koostenäkymiä datasta. 

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/235
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/133
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/236
```

**Comment by SannaJokela** [comment]
Duplikaatti #148
