### ISSUE TITLE
3. Tietojen tarkastelu

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#18]
Paikkatietoasiantuntija avaa paikkatietoprojektin ja tarkastelee näkymää. Projekti ja sen paikkatietotasot ovat EUREF-FIN koordinaattijärjestelmässä. Projektissa on valmiina paikkatietotasoja, joissa ei ole ensimmäisellä kerralla sisältöä. 
![Näyttökuva 2024-01-15 123620](https://github.com/GispoCoding/hame-ryhti/assets/158172654/09e31dad-43b7-4cb3-a4d1-9c4160c2dad1)

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```Tietokannan luonti mk-kaavatietomallin käsitemallin perusteella, eri geometria/kaavakohde-tyypit eroteltuna

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```QGIS-projektin luonti tietokantaan käyttäjätarinan 3. perusteella (ota mallia GeoPackagesta tarvittaessa). Toteutus suomenkielellä testivaiheessa

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```Ruotsinkielinen QGIS-projekti
