### ISSUE TITLE
T22 Muiden liitetiedostojen kuin päätösasiakirjojen liittäminen tietomalliin

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#192]
Paikkatietoasiantuntijana haluan liittää liiteasiakirjoja kaava-aineistoon joko suoraan tietokantaan tallentamalla tai linkittämällä tietoon URLin.

Eroavat päätösasiakirjoista, sillä vain tietyt asiakirjat ovat pakollisia ks. #135 

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/193
- [x] Toteuta asiakirjan liitetiedoston käsittely tietomallissa.
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/238
```

**Comment by SannaJokela** [comment]
Käsitellään samoin kuin muut asiakirjat
