### ISSUE TITLE
KT01Tietokantapohjainen kaava

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#28]
```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/42
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/43
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/45
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/46
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/48
```

**Comment by rlindb** [comment]
Tämä on nyt väärä ketju, tämä pitäisi saada pois.
