### ISSUE TITLE
T33 Ohjeet tietokantayhteyden ottamiseen ESRIn ja QGISin avulla

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#43]
Paikkatietoasiantuntijana haluan saada ohjeet tietokantayhteyden ottamiseen eri paikkatietojärjestelmistä, koska maakuntakaavoitusta tehdään mahdollisesti tulevaisuudessa sekä ESRIn että QGISin avulla, jotta tietojen välitys näistä ohjelmistoista Lounaistiedon tietokantaan on mahdollista.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/9
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/215
- [x] Ohjeet ArcGISillä tietokantayhteyden ottamiseen
```

**Comment by SannaJokela** [comment]
Tätä testattiin hankkeessa eikä sitä saatu toimimaan. Sovittu, että Filegeodatabase tuotetaan hame-ryhti-mallia mukaellen ja se konvertoidaan erikseen PostGISiin.
