### ISSUE TITLE
T67 QGIS-projektiin geometriatasot

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#55]
Paikkatietoasiantuntijana haluan, että paikkatietoprojekti sisältää seuraavat tasot: kaava, aluevaraus, maankäytön kohteet, osa-alueet, viivat ja pisteet.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/5
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/7
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/8
```
