### ISSUE TITLE
T80 QGIS-projekti sisältää taulut valmiilla lomakkeilla

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#56]
Paikkatietoasiantuntija haluan, että tasot ovat ensimmäisellä avauksella tyhjiä ja niillä ei ole visualisointeja valmiina ja niille on luotu valmiit ominaisuustietolomakkeet ja koodistoja voidaan hyödyntää alasvetovalikoineen.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/2
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/25
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/6
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/216
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/217
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/15
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/7
```
