### ISSUE TITLE
Paikkatietoasiantuntijana haluan, että ns. kaavakohdekohtaiset määräykset (esimerkiksi kaavamääräysryhmä: Teollisuusalue, jonka sanallisena määräyksenä: “Vain tällä kohteella määräys eroaa muista teollisuusalueista”) voitaisiin käsitellä ilman kaavamääräysryhmää, jotta luokitteluun ei tule kahta saman nimistä otsikkoa/kirjaintunnusta, koska kaavamääräysryryhmän otsikko/kirjaintunnus päättää luokittelun.

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#78]
```[tasklist]
### Tasks
- [x] https://github.com/GispoCoding/hame-ryhti/issues/79
- [x] https://github.com/GispoCoding/hame-ryhti/issues/80
- [x] https://github.com/GispoCoding/hame-ryhti/issues/81
- [x] https://github.com/GispoCoding/hame-ryhti/issues/82
```

**Comment by SannaJokela** [comment]
Duplikaatti #38
