### ISSUE TITLE
T78 Kehittämisperiaatemerkintöjen toteutus ilman käyttötarkoituskohdistusta

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#85]
Tietojärjestelmäkehittäjänä haluan, että kehittämisperiaatemerkinnät voisi toteuttaa siten, että kaavamääräyslajina on jokin kaavamääräyslaji, ja sen lisätietona olisi tyyppinä kehittämisvyöhyke, jolloin muodostuu kaavamääräyslajin kehittämisvyöhyke, koska näin ei tarvitse tehdä käyttötarkoituskohdistusta.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/89
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/226
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/116
```

**Comment by SannaJokela** [comment]
#115 toistoa aiemmille. Suljetaan.
