### ISSUE TITLE
T64 Lisätiedonlajienkoodien otsikointi ja ryhmittely siten, että samasta ryhmästä voi valita vain yhden koodin

### ISSUE THREAD

**Issue by rlindb** [GispoCoding/hame-ryhti#93]
Paikkatietoasiantuntijana haluan, että lisätiedonlajien osalta alasvetovalikoissa olevat koodit ovat toisensa poissulkevia.

```[tasklist]
### Tasks
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/94
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/95
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/96
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/97
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/7
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/8
- [ ] https://github.com/GispoCoding/hame-ryhti/issues/15
```

```[tasklist]
### Tasks
```
